{
  "uid" : "63e1adad1d768cda",
  "name" : "POST db_create",
  "fullName" : "tests_api.test_bd.TestPOST#test_post_db_create",
  "historyId" : "0b53e71177b12ce964a75d76d7986dbc",
  "time" : {
    "start" : 1741481794223,
    "stop" : 1741481794223,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "KeyError: 'token'",
  "statusTrace" : "self = <Response [502]>, kwargs = {}\n\n    def json(self, **kwargs):\n        r\"\"\"Returns the json-encoded content of a response, if any.\n    \n        :param \\*\\*kwargs: Optional arguments that ``json.loads`` takes.\n        :raises requests.exceptions.JSONDecodeError: If the response body does not\n            contain valid json.\n        \"\"\"\n    \n        if not self.encoding and self.content and len(self.content) > 3:\n            # No encoding set. JSON RFC 4627 section 3 states we should expect\n            # UTF-8, -16 or -32. Detect which one to use; If the detection or\n            # decoding fails, fall back to `self.text` (using charset_normalizer to make\n            # a best guess).\n            encoding = guess_json_utf(self.content)\n            if encoding is not None:\n                try:\n                    return complexjson.loads(self.content.decode(encoding), **kwargs)\n                except UnicodeDecodeError:\n                    # Wrong UTF codec detected; usually because it's not UTF-8\n                    # but some other 8-bit codec.  This is an RFC violation,\n                    # and the server didn't bother to tell us what codec *was*\n                    # used.\n                    pass\n                except JSONDecodeError as e:\n                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n    \n        try:\n>           return complexjson.loads(self.text, **kwargs)\n\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/models.py:974: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/json/__init__.py:346: in loads\n    return _default_decoder.decode(s)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/json/decoder.py:338: in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <json.decoder.JSONDecoder object at 0x7f1c3cce7260>\ns = '<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n'\nidx = 0\n\n    def raw_decode(self, s, idx=0):\n        \"\"\"Decode a JSON document from ``s`` (a ``str`` beginning with\n        a JSON document) and return a 2-tuple of the Python\n        representation and the index in ``s`` where the document ended.\n    \n        This can be used to decode a JSON document from a string that may\n        have extraneous data at the end.\n    \n        \"\"\"\n        try:\n            obj, end = self.scan_once(s, idx)\n        except StopIteration as err:\n>           raise JSONDecodeError(\"Expecting value\", s, err.value) from None\nE           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/json/decoder.py:356: JSONDecodeError\n\nDuring handling of the above exception, another exception occurred:\n\n    @pytest.fixture()\n    def get_token():\n        \"\"\"\n        Method return:\\n\n        token: str\\n\n        body: dict\\n\n        new_password: str\\n\n        old_password: str\\n\n        email: str\n        :returns: token: str, body: dict, new_password: str, old_password:str, email: str\n        \"\"\"\n        load_dotenv()\n        email = os.getenv('EMAIL')\n        old_password = os.getenv('PASSWORD')\n        new_password = '123456789'\n        try:\n            body = {\"email\": email, \"password\": f'{old_password}'}\n            result = requests.post('https://dbend.areso.pro/login', json=body)\n>           token = result.json()['token']\n\nconftest.py:65: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [502]>, kwargs = {}\n\n    def json(self, **kwargs):\n        r\"\"\"Returns the json-encoded content of a response, if any.\n    \n        :param \\*\\*kwargs: Optional arguments that ``json.loads`` takes.\n        :raises requests.exceptions.JSONDecodeError: If the response body does not\n            contain valid json.\n        \"\"\"\n    \n        if not self.encoding and self.content and len(self.content) > 3:\n            # No encoding set. JSON RFC 4627 section 3 states we should expect\n            # UTF-8, -16 or -32. Detect which one to use; If the detection or\n            # decoding fails, fall back to `self.text` (using charset_normalizer to make\n            # a best guess).\n            encoding = guess_json_utf(self.content)\n            if encoding is not None:\n                try:\n                    return complexjson.loads(self.content.decode(encoding), **kwargs)\n                except UnicodeDecodeError:\n                    # Wrong UTF codec detected; usually because it's not UTF-8\n                    # but some other 8-bit codec.  This is an RFC violation,\n                    # and the server didn't bother to tell us what codec *was*\n                    # used.\n                    pass\n                except JSONDecodeError as e:\n                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n    \n        try:\n            return complexjson.loads(self.text, **kwargs)\n        except JSONDecodeError as e:\n            # Catch JSON-related errors and raise as requests.JSONDecodeError\n            # This aliases json.JSONDecodeError and simplejson.JSONDecodeError\n>           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nE           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/models.py:978: JSONDecodeError\n\nDuring handling of the above exception, another exception occurred:\n\n    @pytest.fixture()\n    def get_token():\n        \"\"\"\n        Method return:\\n\n        token: str\\n\n        body: dict\\n\n        new_password: str\\n\n        old_password: str\\n\n        email: str\n        :returns: token: str, body: dict, new_password: str, old_password:str, email: str\n        \"\"\"\n        load_dotenv()\n        email = os.getenv('EMAIL')\n        old_password = os.getenv('PASSWORD')\n        new_password = '123456789'\n        try:\n            body = {\"email\": email, \"password\": f'{old_password}'}\n            result = requests.post('https://dbend.areso.pro/login', json=body)\n            token = result.json()['token']\n            if token != {}:\n                new_password, old_password = old_password, new_password\n            Checking.check_status_code(result, 200)\n            return token, body, new_password, old_password, email\n        except Exception as ex:\n            print(ex)\n            old_password, new_password = new_password, old_password\n            body = {\"email\": email, \"password\": f'{old_password}'}\n            result = requests.post('https://dbend.areso.pro/login', json=body)\n>           token = result.json()['token']\nE           KeyError: 'token'\n\nconftest.py:75: KeyError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "get_token",
    "time" : {
      "start" : 1741481794223,
      "stop" : 1741481795513,
      "duration" : 1290
    },
    "status" : "broken",
    "statusMessage" : "KeyError: 'token'\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Oblache/Oblache/conftest.py\", line 75, in get_token\n    token = result.json()['token']\n            ~~~~~~~~~~~~~^^^^^^^^^\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "POST"
  }, {
    "name" : "parentSuite",
    "value" : "tests_api"
  }, {
    "name" : "subSuite",
    "value" : "TestPOST"
  }, {
    "name" : "host",
    "value" : "fv-az2035-376"
  }, {
    "name" : "thread",
    "value" : "2465-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests_api.test_bd"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 112,
        "broken" : 11,
        "skipped" : 0,
        "passed" : 1,
        "unknown" : 0,
        "total" : 124
      },
      "items" : [ {
        "uid" : "db03dd6890ee337a",
        "reportUrl" : "https://lambotik.github.io/Oblache/335//#testresult/db03dd6890ee337a",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741395118010,
          "stop" : 1741395118658,
          "duration" : 648
        }
      }, {
        "uid" : "df7fd8184fa5a32c",
        "reportUrl" : "https://lambotik.github.io/Oblache/334//#testresult/df7fd8184fa5a32c",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741309516785,
          "stop" : 1741309517846,
          "duration" : 1061
        }
      }, {
        "uid" : "c0c740a50c0f4426",
        "reportUrl" : "https://lambotik.github.io/Oblache/23//#testresult/c0c740a50c0f4426",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741273252477,
          "stop" : 1741273253538,
          "duration" : 1061
        }
      }, {
        "uid" : "7447c6d7af8a01ba",
        "reportUrl" : "https://lambotik.github.io/Oblache/22//#testresult/7447c6d7af8a01ba",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741273009359,
          "stop" : 1741273009982,
          "duration" : 623
        }
      }, {
        "uid" : "ac3b63dec572c3b0",
        "reportUrl" : "https://lambotik.github.io/Oblache/21//#testresult/ac3b63dec572c3b0",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741272396687,
          "stop" : 1741272397304,
          "duration" : 617
        }
      }, {
        "uid" : "628fb78e05924da1",
        "reportUrl" : "https://lambotik.github.io/Oblache/20//#testresult/628fb78e05924da1",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741271069105,
          "stop" : 1741271070166,
          "duration" : 1061
        }
      }, {
        "uid" : "ccf0a676ffe34134",
        "reportUrl" : "https://lambotik.github.io/Oblache/19//#testresult/ccf0a676ffe34134",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741270250647,
          "stop" : 1741270251697,
          "duration" : 1050
        }
      }, {
        "uid" : "d5172c069b008e40",
        "reportUrl" : "https://lambotik.github.io/Oblache/333//#testresult/d5172c069b008e40",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741223071869,
          "stop" : 1741223072478,
          "duration" : 609
        }
      }, {
        "uid" : "90f0058cffd8840b",
        "reportUrl" : "https://lambotik.github.io/Oblache/332//#testresult/90f0058cffd8840b",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741136672216,
          "stop" : 1741136672910,
          "duration" : 694
        }
      }, {
        "uid" : "e0808e591c14719",
        "reportUrl" : "https://lambotik.github.io/Oblache/331//#testresult/e0808e591c14719",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1741050268950,
          "stop" : 1741050269581,
          "duration" : 631
        }
      }, {
        "uid" : "64953ee95c05d8a9",
        "reportUrl" : "https://lambotik.github.io/Oblache/330//#testresult/64953ee95c05d8a9",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740963958348,
          "stop" : 1740963959096,
          "duration" : 748
        }
      }, {
        "uid" : "8825727afe9e40bc",
        "reportUrl" : "https://lambotik.github.io/Oblache/329//#testresult/8825727afe9e40bc",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740877657925,
          "stop" : 1740877658674,
          "duration" : 749
        }
      }, {
        "uid" : "23a038ee93d8037f",
        "reportUrl" : "https://lambotik.github.io/Oblache/328//#testresult/23a038ee93d8037f",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740791295186,
          "stop" : 1740791295795,
          "duration" : 609
        }
      }, {
        "uid" : "66548d7c2dd2638c",
        "reportUrl" : "https://lambotik.github.io/Oblache/327//#testresult/66548d7c2dd2638c",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740704626342,
          "stop" : 1740704626956,
          "duration" : 614
        }
      }, {
        "uid" : "619a78b3e8948cc2",
        "reportUrl" : "https://lambotik.github.io/Oblache/326//#testresult/619a78b3e8948cc2",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 500",
        "time" : {
          "start" : 1740618203225,
          "stop" : 1740618203965,
          "duration" : 740
        }
      }, {
        "uid" : "7ff52ba6d5c9c535",
        "reportUrl" : "https://lambotik.github.io/Oblache/325//#testresult/7ff52ba6d5c9c535",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740531807450,
          "stop" : 1740531808097,
          "duration" : 647
        }
      }, {
        "uid" : "1cb74400e3007e6c",
        "reportUrl" : "https://lambotik.github.io/Oblache/324//#testresult/1cb74400e3007e6c",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740445415645,
          "stop" : 1740445416378,
          "duration" : 733
        }
      }, {
        "uid" : "b58210ada31c789a",
        "reportUrl" : "https://lambotik.github.io/Oblache/323//#testresult/b58210ada31c789a",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740359081360,
          "stop" : 1740359082388,
          "duration" : 1028
        }
      }, {
        "uid" : "8aa31429cebc5ae2",
        "reportUrl" : "https://lambotik.github.io/Oblache/322//#testresult/8aa31429cebc5ae2",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740272811670,
          "stop" : 1740272812688,
          "duration" : 1018
        }
      }, {
        "uid" : "54ad15cb576e09a6",
        "reportUrl" : "https://lambotik.github.io/Oblache/321//#testresult/54ad15cb576e09a6",
        "status" : "failed",
        "statusDetails" : "AssertionError: Incorrect status code: 403",
        "time" : {
          "start" : 1740186037525,
          "stop" : 1740186038282,
          "duration" : 757
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "63e1adad1d768cda.json",
  "parameterValues" : [ ]
}